FROM python:3.12-slim-bookworm

WORKDIR /opt/remnashop

COPY pyproject.toml .
COPY uv.lock .
COPY docker-entrypoint.sh .

RUN pip install --no-cache-dir uv && uv sync --frozen

ENV UVICORN_RELOAD_ENABLED=true
ENV PATH="/opt/remnashop/.venv/bin:$PATH"

CMD ["/bin/sh", "docker-entrypoint.sh"]
